//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCvsite.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCvsiteEntities1 : DbContext
    {
        public DbCvsiteEntities1()
            : base("name=DbCvsiteEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TablHakkimda> TablHakkimda { get; set; }
        public virtual DbSet<TblAdmin> TblAdmin { get; set; }
        public virtual DbSet<TblDeneyimler> TblDeneyimler { get; set; }
        public virtual DbSet<TblEgitim> TblEgitim { get; set; }
        public virtual DbSet<TblHobilerim> TblHobilerim { get; set; }
        public virtual DbSet<Tbliletisim> Tbliletisim { get; set; }
        public virtual DbSet<TblSertifikalar> TblSertifikalar { get; set; }
        public virtual DbSet<TblSosyalMedyalar> TblSosyalMedyalar { get; set; }
        public virtual DbSet<TblYeteneklerim> TblYeteneklerim { get; set; }
    }
}
